FROM python:3.11-alpine

WORKDIR /usr/src/app

# переменные окружения для python
#не создавать файлы кэша .pyc
ENV PYTHONDONTWRITEBYTECODE 1
# не помещать в буфер потоки stdout и stderr
ENV PYTHONUNBUFFERED 1

RUN apk update \
  && apk add postgresql-dev gcc python3-dev musl-dev linux-headers

RUN python3 -m venv venv

RUN source venv/bin/activate

RUN pip install wheel Flask docxtpl uwsgi redis rq python-dotenv psycopg2 pyjwt py-bcrypt